name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "* * 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies1'
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Setup git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          
      
        
      - name: '开始运行ics'
        run: python aaa.py
       
      - name: commit
        run: |


          git config --local user.email "zhangzhiwen91@gmail.com"
          git config --local user.name "jast90"
          git add .
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" 
     
          
      - name: Push changes
        uses: ad-m/github-push-action@master
      
